### ISSUE TITLE
Transaction History Page UI

### ISSUE THREAD

**Issue by canismajor88** [canismajor88/CashHandler#17]

**Comment by zjwonder** [comment]
![image](https://user-images.githubusercontent.com/60233767/139600738-b0f05a94-d831-4605-9df4-f5e815fa3dc9.png)
![image](https://user-images.githubusercontent.com/60233767/139600751-bcdf4798-9209-4c09-b00e-9d7863bb844e.png)

**Comment by zjwonder** [comment]
Screenshots above are an initial prototype of web app. Upon successful login, this is the page that the user should be sent to.

**Comment by zjwonder** [comment]
![Flowchart](https://user-images.githubusercontent.com/60233767/139601417-e76a6dc1-9055-454a-a97c-e817e557aa8a.png)

UI Navigation flowchart

Also I just noticed that I forgot to include 'Balance Wallet' on the navbar prototypes.
